name: chatwoot_sdk
description: A flutter client sdk for chatwoot. Integrate Chatwoot flutter client into your flutter app and talk to your visitors/users in real time.
version: 0.0.9
homepage: https://github.com/chatwoot/chatwoot-flutter-sdk

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
